version: '2'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
      - '1080:1080'
    volumes:
      - '.:/app'
      - logstash-config:/app/logstash/config/
    env_file:
      - '.env'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g

  logstash:
    image: logstash:7.8.1
    volumes:
      - logstash-config:/app/logstash/config/
    environment:
      - path.config=/app/logstash/config/logstash.conf
      - config.reload.automatic=true

  kibana:
    image: kibana:7.8.1
    ports:
      - 5602:5601

  elasticsearch_test:
    image: elasticsearch:7.8.1
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - esdata_test:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g

volumes:
  logstash-config:
  postgres:
  esdata:
  esdata_test:
